version: "3"
services:
  go:
    build:
      context: .
      dockerfile: ./docker/golang/Dockerfile
    container_name: go
    volumes:
      - ./go-app:/app/go
    ports:
      - 8000:8000
    environment:
      - GOOSE_DRIVER=mysql
      - GOOSE_DBSTRING=docker:docker@tcp(db:3306)/time_scheduler
    depends_on:
      - db
    networks:
      - time-scheduler_backend
  db:
    container_name: db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: time_scheduler
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: "Asia/Tokyo"
    volumes:
      - ./docker/mysql/mysql_data:/var/lib/mysql
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - time-scheduler_backend
networks:
  time-scheduler_backend:
