name: Go Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Run Go Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.5
      - name: build db container
        run: docker-compose up -d db
      - name: Change directory
        run: |
          cd go-app
          ls
          go get -v -t -d ./...
          go test ./...